export const profile = {
  name: 'Enqi Jing',
  role: 'Software engineer and researcher',
  title: 'Risk Intelligence Engineer and Researcher',
  description:
    'Enqi Jing is a software engineer and researcher working across distributed systems, machine learning, and risk intelligence.',
  bio: [
    'I studied Computer Science and Predictive Modelling at the University of Warwick. My work has included industrial data, cyber-risk research, AI evaluation, and distributed trading systems.',
    'I enjoy moving between research and implementation. That might mean comparing models on noisy process data, tracing unusual behaviour, or building infrastructure that needs to stay observable when something goes wrong.',
    'I am especially interested in risk, reliability, and decision-making in connected engineering, energy, and financial systems.',
  ],
  email: 'jingenqi724@gmail.com',
  location: 'United Kingdom',
  github: 'https://github.com/jingenqi',
  linkedin: 'https://www.linkedin.com/in/enqi-jing-b36600157/',
  website: 'https://jingenqi.tech',
  resumePath: '/Enqi_Jing_Resume_File.pdf',
  availability: 'Interested in research roles, engineering work, and doctoral study.',
  skills: {
    programming: ['Python', 'Java', 'SQL', 'C++', 'Go'],
    machineLearning: [
      'PyTorch',
      'scikit-learn',
      'Keras',
      'Regression',
      'Clustering',
      'Anomaly detection',
      'NLP',
      'Time-series modelling',
      'Trajectory modelling',
    ],
    security: [
      'Cyber-risk identification',
      'Threat analysis',
      'Anomaly detection',
      'Failure monitoring',
    ],
    systems: [
      'Asynchronous programming',
      'Message queues',
      'State-machine orchestration',
      'Distributed coordination',
      'REST APIs',
      'FastAPI',
      'NATS JetStream',
    ],
    infrastructure: [
      'PostgreSQL',
      'TimescaleDB',
      'MySQL',
      'Docker',
      'Linux',
      'Git',
      'AWS',
    ],
  },
};
